схема БД
jsavchenkova/java-filmorate pull request #8
Opened 2024-06-13 20:05 UTC by jsavchenkova

2024-06-14 17:36 UTC, Ivivchik reviewed
Хорошая работа) Есть пару комментариев касательно схемы:
1. Для соблюдения [второй нормальной формы](https://info-comp.ru/second-normal-form), таблица user должна содержать первичный ключ
2. Свойство жанр, согласно ТЗ , относится к сущности фильм, не к user
3. Так как мы будем использовать postgres, типы данных должны соответствовать [документации](https://postgrespro.ru/docs/postgresql/9.4/datatype). Типа login нет в postgres

2024-06-14 17:51 UTC, Ivivchik commented
И пару полезных ссылок:
1. [Оформление кода в readme для подсветки синтаксиса языка](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#creating-diagrams). Повышает читабельность, сразу видно ключевые слова языка
2. Для читабельности sql запросов рекомендуется придерживаться [sql style guide](https://raw.githubusercontent.com/treffynnon/sqlstyle.guide/gh-pages/_includes/sqlstyle.guide.md). Из самых основных это писать все ключевые слова(SELECT, FROM, WHERE и так далее) в апперкейсе. Сразу отличаешь где ключевые слова, где поля таблиц)

2024-07-03 15:12 UTC, kriwsha requested changes

2024-07-04 18:47 UTC, kriwsha approved these changes

2024-07-04 18:55 UTC, merged